name: brigadier_dart
description: brigadier but in dart
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  string_validator: null
  quiver: null
  system_info: null

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  benchmark_harness: ^2.0.0
  mockito:
  build_runner:
